captainVersion: 4
services:
    $$cap_appname-db:
        image: supabase/postgres:$$cap_postgres_version
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: supabase_admin
            POSTGRES_PASSWORD: $$cap_postgres_password
            POSTGRES_DB: postgres
        restart: always
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-meta:
        depends_on:
            - $$cap_appname-db
        image: supabase/postgres-meta:$$cap_meta_version
        environment:
            PG_META_PORT: '8080'
            PG_META_DB_HOST: srv-captain--$$cap_appname-db
            PG_META_DB_PORT: '5432'
            PG_META_DB_NAME: postgres
            PG_META_DB_USER: supabase_admin
            PG_META_DB_PASSWORD: $$cap_postgres_password
        restart: always
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-auth:
        depends_on:
            - $$cap_appname-db
        image: supabase/gotrue:$$cap_gotrue_version
        environment:
            GOTRUE_API_HOST: '0.0.0.0'
            GOTRUE_API_PORT: '9999'
            API_EXTERNAL_URL: https://$$cap_appname-auth.$$cap_root_domain
            GOTRUE_DB_DRIVER: postgres
            GOTRUE_DB_DATABASE_URL: postgres://supabase_admin:$$cap_postgres_password@srv-captain--$$cap_appname-db:5432/postgres?search_path=auth
            GOTRUE_SITE_URL: $$cap_site_url
            GOTRUE_URI_ALLOW_LIST: $$cap_allowed_urls
            GOTRUE_DISABLE_SIGNUP: 'false'
            GOTRUE_JWT_ADMIN_ROLES: service_role
            GOTRUE_JWT_AUD: authenticated
            GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
            GOTRUE_JWT_EXP: '3600'
            GOTRUE_JWT_SECRET: $$cap_jwt_secret
            GOTRUE_EXTERNAL_EMAIL_ENABLED: 'true'
            GOTRUE_MAILER_AUTOCONFIRM: $$cap_auto_confirm
            GOTRUE_SMTP_ADMIN_EMAIL: $$cap_smtp_admin_email
            GOTRUE_MAILER_URLPATHS_INVITE: /auth/v1/verify
            GOTRUE_MAILER_URLPATHS_CONFIRMATION: /auth/v1/verify
            GOTRUE_MAILER_URLPATHS_RECOVERY: /auth/v1/verify
            GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: /auth/v1/verify
        restart: always
        caproverExtra:
            containerHttpPort: '9999'

    $$cap_appname-rest:
        depends_on:
            - $$cap_appname-db
        image: postgrest/postgrest:$$cap_postgrest_version
        environment:
            PGRST_DB_URI: postgres://supabase_admin:$$cap_postgres_password@srv-captain--$$cap_appname-db:5432/postgres
            PGRST_DB_SCHEMAS: public,storage,graphql_public
            PGRST_DB_ANON_ROLE: anon
            PGRST_JWT_SECRET: $$cap_jwt_secret
            PGRST_DB_USE_LEGACY_GUCS: 'false'
            PGRST_APP_SETTINGS_JWT_SECRET: $$cap_jwt_secret
            PGRST_APP_SETTINGS_JWT_EXP: '3600'
        restart: always
        caproverExtra:
            containerHttpPort: '3000'

    $$cap_appname-studio:
        depends_on:
            - $$cap_appname-db
            - $$cap_appname-meta
        image: supabase/studio:$$cap_studio_version
        environment:
            STUDIO_PG_META_URL: http://srv-captain--$$cap_appname-meta:8080
            POSTGRES_PASSWORD: $$cap_postgres_password
            DEFAULT_ORGANIZATION_NAME: $$cap_org_name
            DEFAULT_PROJECT_NAME: $$cap_project_name
            SUPABASE_URL: https://$$cap_appname-rest.$$cap_root_domain
            SUPABASE_PUBLIC_URL: https://$$cap_appname-rest.$$cap_root_domain
            SUPABASE_ANON_KEY: $$cap_anon_key
            SUPABASE_SERVICE_KEY: $$cap_service_role_key
            AUTH_JWT_SECRET: $$cap_jwt_secret
            NEXT_PUBLIC_ENABLE_LOGS: 'false'
            NEXT_ANALYTICS_BACKEND_PROVIDER: postgres
        restart: always
        caproverExtra:
            containerHttpPort: '3000'

caproverOneClickApp:
    variables:
        - id: $$cap_postgres_version
          label: PostgreSQL Version
          defaultValue: '15.6.1.146'
          description: 'Supabase PostgreSQL version'
          validRegex: /.+/

        - id: $$cap_meta_version
          label: Postgres-Meta Version
          defaultValue: v0.84.2
          description: 'Postgres-Meta version'
          validRegex: /.+/

        - id: $$cap_gotrue_version
          label: GoTrue Version
          defaultValue: v2.164.0
          description: 'GoTrue (Auth) version'
          validRegex: /.+/

        - id: $$cap_postgrest_version
          label: PostgREST Version
          defaultValue: v12.2.3
          description: 'PostgREST version'
          validRegex: /.+/

        - id: $$cap_studio_version
          label: Studio Version
          defaultValue: '20241202-71e5240'
          description: 'Studio Dashboard version'
          validRegex: /.+/

        - id: $$cap_postgres_password
          label: PostgreSQL Password
          defaultValue: $$cap_gen_random_hex(24)
          description: 'Database password (min 12 chars)'
          validRegex: /.{12,}/

        - id: $$cap_jwt_secret
          label: JWT Secret
          defaultValue: $$cap_gen_random_hex(32)
          description: 'JWT signing secret (min 32 chars)'
          validRegex: /.{32,}/

        - id: $$cap_anon_key
          label: Anon Key (JWT)
          defaultValue: ''
          description: 'Anonymous API key - generate at https://supabase.com/docs/guides/self-hosting#api-keys'
          validRegex: /.*/

        - id: $$cap_service_role_key
          label: Service Role Key (JWT)
          defaultValue: ''
          description: 'Service role API key - generate at https://supabase.com/docs/guides/self-hosting#api-keys'
          validRegex: /.*/

        - id: $$cap_site_url
          label: Site URL
          defaultValue: http://localhost:3000
          description: 'Your frontend app URL'
          validRegex: /.+/

        - id: $$cap_allowed_urls
          label: Allowed Redirect URLs
          defaultValue: '*'
          description: 'Comma-separated redirect URLs'
          validRegex: /.+/

        - id: $$cap_auto_confirm
          label: Auto Confirm Email
          defaultValue: 'true'
          description: 'Auto-confirm without SMTP'
          validRegex: /^(true|false)$/

        - id: $$cap_smtp_admin_email
          label: Admin Email
          defaultValue: admin@example.com
          description: 'Admin email'
          validRegex: /.+/

        - id: $$cap_org_name
          label: Organization Name
          defaultValue: My Organization
          description: 'Organization name in Studio'
          validRegex: /.+/

        - id: $$cap_project_name
          label: Project Name
          defaultValue: My Project
          description: 'Project name in Studio'
          validRegex: /.+/

    instructions:
        start: |-
            Supabase - The Open Source Firebase Alternative

            This deploys:
            - PostgreSQL with Supabase extensions
            - GoTrue (Authentication)
            - PostgREST (REST API)
            - Studio (Dashboard)

            IMPORTANT: Generate JWT keys before deploying!
            Use the JWT_SECRET value you set, then run:

            JWT_SECRET="YOUR_JWT_SECRET"
            HEADER=$(echo -n '{"alg":"HS256","typ":"JWT"}' | base64 -w 0 | tr '+/' '-_' | tr -d '=')
            ANON=$(echo -n '{"role":"anon","iss":"supabase","iat":1735128000,"exp":1893456000}' | base64 -w 0 | tr '+/' '-_' | tr -d '=')
            echo "ANON_KEY: ${HEADER}.${ANON}.$(echo -n "${HEADER}.${ANON}" | openssl dgst -sha256 -hmac "${JWT_SECRET}" -binary | base64 -w 0 | tr '+/' '-_' | tr -d '=')"
            SVC=$(echo -n '{"role":"service_role","iss":"supabase","iat":1735128000,"exp":1893456000}' | base64 -w 0 | tr '+/' '-_' | tr -d '=')
            echo "SERVICE_KEY: ${HEADER}.${SVC}.$(echo -n "${HEADER}.${SVC}" | openssl dgst -sha256 -hmac "${JWT_SECRET}" -binary | base64 -w 0 | tr '+/' '-_' | tr -d '=')"

        end: |-
            Supabase deployed! 🎉

            Services:
            - Studio: https://$$cap_appname-studio.$$cap_root_domain
            - REST API: https://$$cap_appname-rest.$$cap_root_domain
            - Auth: https://$$cap_appname-auth.$$cap_root_domain

            SAVE THESE:
            - DB Password: $$cap_postgres_password
            - JWT Secret: $$cap_jwt_secret

            Next: Enable HTTPS on all apps!

    displayName: Supabase (Full Stack)
    isOfficial: false
    description: Open source Firebase alternative - PostgreSQL, Auth, REST API, Studio
    documentation: https://supabase.com/docs/guides/self-hosting
